# Generated by Django 5.0.7 on 2024-07-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_reader_contact_reader_full_name_alter_reader_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='phone_number',
        ),
    ]
