# Generated by Django 5.0.7 on 2024-07-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_reader_gender_remove_reader_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('allocated_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.reader')),
            ],
        ),
    ]
